### ISSUE TITLE
Update to python-xlib 0.16 breaks AutoKey

### ISSUE THREAD

**Issue by cryzed** [guoci/autokey-py3#33]
After the recent update to [python-xlib](https://pypi.python.org/pypi/python-xlib) 0.16 AutoKey seems to be broken:

    $ autokey-qt
    Exception in thread XInterface-thread:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.5/site-packages/autokey/interface.py", line 1040, in run
        self.recordDisplay.record_enable_context(self.ctx, self.__processEvent)
      File "/usr/lib/python3.5/site-packages/Xlib/ext/record.py", line 243, in enable_context
        context = context)
      File "/usr/lib/python3.5/site-packages/Xlib/ext/record.py", line 220, in __init__
        rq.ReplyRequest.__init__(self, *args, **keys)
      File "/usr/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1361, in __init__
        self.reply()
      File "/usr/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1373, in reply
        self._display.send_and_recv(request = self._serial)
      File "/usr/lib/python3.5/site-packages/Xlib/protocol/display.py", line 576, in send_and_recv
        gotreq = self.parse_response(request)
      File "/usr/lib/python3.5/site-packages/Xlib/protocol/display.py", line 668, in parse_response
        gotreq = self.parse_request_response(request) or gotreq
      File "/usr/lib/python3.5/site-packages/Xlib/protocol/display.py", line 756, in parse_request_response
        req._parse_response(self.data_recv[:self.recv_packet_len])
      File "/usr/lib/python3.5/site-packages/Xlib/ext/record.py", line 224, in _parse_response
        self._callback(r)
      File "/usr/lib/python3.5/site-packages/autokey/interface.py", line 1054, in __processEvent
        if not len(reply.data) or reply.data[0] < 2:
    TypeError: unorderable types: str() < int()

I'm running Arch Linux with the recently updated [python-xlib 0.16-1](https://www.archlinux.org/packages/community/any/python-xlib/). This is very likely because until recently [LiuLang's patches](https://github.com/LiuLang/python3-xlib) were used from [this](https://aur.archlinux.org/packages/python-xlib/) AUR package, but now there's an actual [official release](https://github.com/python-xlib/python-xlib/releases/tag/0.16) with Python 3 support, causing the AUR package to be overwritten during the next system-update.

**Comment by MBuchaus** [comment]
Thanks cryzed.. I have found and can confirm the same issue.. I just noticed Autokey not working then ran it autokey-gtl -l  and noticed the exact error your getting and posted here.

Marty

**Comment by cryzed** [comment]
You can fix this issue on Arch Linux by installing [python-xlib from the AUR](https://aur.archlinux.org/packages/python-xlib/), which installs [LiuLang's fork](https://aur.archlinux.org/packages/python-xlib/) of python-xlib. This was the python-xlib version which was most likely installed by your AUR helper, but was overwritten by the python-xlib in the official repositories recently.

**Comment by MBuchaus** [comment]
Nice yep that fixed my issue.. Thanks again Cryzed.

**Comment by cryzed** [comment]
> I've also noticed how much I depend on this application and its function in my work flow.

Exactly the same here: I especially depend on the abbreviation functionality, which allows me to substitute phrases that I type.

**Comment by cryzed** [comment]
@MBuchaus: [Here](https://github.com/cryzed/bin/blob/master/hotstrings) it is with a [small readme](https://github.com/cryzed/bin#hotstrings). This is the feature I exclusively use and really rely on; if it's the same for you and this fork of AutoKey stops working for you at some point, maybe give it a try -- it's much lighter too: You only need Python 3 and python-xlib.

**Comment by guoci** [comment]
I have made some changes to the code to make it work on both the official release and LiuLang's release.

**Comment by cryzed** [comment]
Awesome, thanks! Seems I was mistaken regarding the activity of the project -- sorry.

**Comment by MBuchaus** [comment]
How does one find the new location in pypi.python.org to edit the PKGBUILD to get the latests code.

**Comment by cryzed** [comment]
Just check [this link](https://pypi.python.org/pypi/python-xlib/), scroll down and copy the link URLs.
