### ISSUE TITLE
Error when defining abbreviations

### ISSUE THREAD

**Issue by kuhanalog** [guoci/autokey-py3#5]
(I am using the development version from GitHub.)
When defining abbreviations for phrases, the following error occured:

Traceback (most recent call last):
  File "/home/username/.local/lib/python3.4/site-packages/autokey/qtui/dialogs.py", line 54, in setData
    if value.toString() == "":
AttributeError: 'str' object has no attribute 'toString'

In the specified file, I have therefore replaced (line 54) 
  if value.toString() == "":
with
  if value == "":
This has resolved the error for my setup; whether this is an appropriate solution in general I don't know.

Thank you for working on this fantastic program!

**Comment by guoci** [comment]
Hi @kuhanalog , can you do a print screen of your autokey GUI? Thanks

**Comment by kuhanalog** [comment]
A screenshot is attached. In case it helps, I am using Kubuntu 14.04.1 with KDE 4.13.3 and Python 3.4.0.
![autokey](https://cloud.githubusercontent.com/assets/5499564/5804096/d60683ba-9fc8-11e4-88aa-a80964dcddf6.png)

**Comment by guoci** [comment]
Thanks. Fixed in cf62d57f4722d133df0101987f315db88fdbaa71
